# Setup
title:        Never Stop "Never Stopping"
tagline:      Until The Robots Takeover
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jonathan Malachowski
  url:        http://jmalacho.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
